export enum QueueNames {
  NOTIFICATION = 'notification',
  Billing = 'billing-service',
  Subscription = 'subscription',
  SSM_SERVICE = 'ssm-service',
  RSM_SERVICE = 'rsm-service-dev',
  CSM_SERVICE_LOG = 'csm-service-log',
  CSM_SERVICE = 'csm-service',
  ODOO_MIDDLEWARE = 'odoo_middelware',
  BPM_SERVICE = 'bpm-service',
  SALES_SERVICE = 'sale-service',
  PRICING_SERVICE = 'pricing-service',
  NOTIFICATION_MANAGERMENT = 'nom-service',
  LOG_SERVICE = 'log-service',
  WB3_MIDDLEWARE = 'wb3-middleware',
  IAM_SERVICE = 'iam-service',
  APIX_SERVICE = 'apix-service',
  MAM_SERVICE = 'mam-service',
  RS_SERVICE = 'rs-service',
}
