export enum OFM_Controllers {
  OFM_OTP = 'otps',
  OFM_SocketListner = 'socket-listeners',
  OFM_SocketListnerLog = 'socket-listener-logs',
  OFM_MNO = 'mnos',
  OFM_MNOConnection = 'mno-connections',
  OFM_MobileNumber = 'mobile-numbers',
  OFM_Provider = 'providers',
  OFM_NumberAssignments = 'number-assignments',
  OFM_NumberAssignmentLogs = 'number-assignment-logs',
  OFM_Farm = 'farms',
  OFM_Partner = 'partners',
  OFM_Report = 'report',
  OFM_OTPRequest = 'otp-requests',
  OFM_Route = 'routes',
  OFM_Utils = 'utils',
  OFM_Webhook = 'webhook',
  OFM_Device = 'devices',
}
