export enum Patterns {
  WEB_APP = 'web-app',
  CREATE_SUBSCRIPTION = 'create-subscription',
  CREATE_SUBSCRIPTION_BLOCKCHAIN = 'create-subscription-blockchain',
  CHANGE_SUBSCRIPTION = 'change-subscription',
  CANCEL_SUBSCRIPTION = 'cancel-subscription',
  DESTROY_SUBSCRIPTION = 'destroy-subscription',

  SUCCESS_PAYMENT = 'success-payment',
  CREATE_SERVICE = 'create-service',
  CHANGE_SERVICE = 'change-service',
  CANCEL_SERVICE = 'cancel-service',
  REGISTER_USER = 'register-user',
  MAIL = 'mail',

  CREATE_CONTAINER = 'create_container',
  CHANGE_CONTAINER = 'change_container',
  CANCEL_CONTAINER = 'cancel_container',
  PAYMENT = 'payment',
}
export enum SubscriptionType {
  CANCEL = 'CANCEL',
  UPGRADE = 'UPGRADE',
  DOWNGRADE = 'DOWNGRADE',
  SUSPEND = 'SUSPEND',
  PAUSE = 'PAUSE',
  UNPAUSE = 'UNPAUSE',
  DESTROY = 'DESTROY',
  RENEW = 'RENEW',
}
export enum Template_Notification_Pattern {
  SR_MAIL = 'success-registration',
  SP_MAIL = 'success-payment',
  SSI_MAIL = 'success-service-initiation',
  S_EXTENSION_MAIL = 'service-extension',
  S_EXPIRATION_MAIL = 'service-expiration',
  D_REVENUA_REPORT_MAIL = 'daily-revenue-report',
  SP_WEBAPP = 'success-payment-web-app',
  SSI_WEBAPP = 'success-service-initiation-web-app',
  ESI_WEBAPP = 'error-service-initiation-web-app',
  S_EXTENSION_WEBAPP = 'service-extension-web-app',
  S_EXPIRATION_WEBAPP = 'service-extension-web-app',
  DAILY_TASK_NOTIFICATION = 'odoo-daily-task-notification',
  SUB_7_DAYS_EXPIRATION = 'subscription-7-days-expiration',
  SUB_3_DAYS_EXPIRATION = 'subscription-3-days-expiration',
  SUB_1_DAY_EXPIRATION = 'subscription-1-day-expiration',
  SUB_ENDED_23_DAYS_EXPIRATION = 'subscription-end-23-days-expiration',
  SUB_ENDED_30_DAYS_EXPIRATION = 'subscription-end-30-days-expiration',
  VERIFICATION_SUCCESS_WORKER_NODE = 'worker-node-verification-success',
}
